---

- hosts: cumulus

  become: true
  roles:
    - ports_interfaces
    - runtime_updates

  vars_prompt:
    - name: vars_prompt_username
      prompt: "Enter your Cumulus username ?"
      private: no

