---

- name: restart prometheusAggregator
  service:
    name: prometheusAggregator
    state: restarted

- name: restart node_exporter
  service:
    name: node_exporter
    state: restarted

- name: enable prometheusAggregator
  systemd:
    name: prometheusAggregator
    enabled: 'yes'
    state: started
  when: (ansible_os_family == "Debian")

- name: enable node_exporter
  systemd:
    name: node_exporter
    enabled: 'yes'
    state: started
  when: (ansible_os_family == "Debian")

- name: enable interface_exporter
  systemd:
    name: interface_exporter
    enabled: 'yes'
    state: started
  when: (ansible_os_family == "Debian")
